### PR TITLE
Exp env dev

### PR DESCRIPTION
**Pull request by vipear**
Changed from unsigned to signed integers for envelope filters.  This allowed for a change in filter form for all except the attack phase. This cost 1 bit of precision but it appears to work OK and it makes the code a little more straightforward  when setting the decay and sustain. It now uses the same normalized values as the linear generating allowing the sustain variable to be shared, saving one 32 bit word. The comments were cleaned up some.

### CODE REVIEW

**Comment by ElectroTechnique** [comment]
Sounds very good. I'll do some more testing. I've added code to retrieve its settings from EEPROM at boot-up, which was missing. I think the way its updating the envelope type setting (using VG...) is fine. Will is still working on the multi-timbral features and I'm hoping it'll work with any further changes he makes. 

I may push your code into the main branch and release it in the next few days.

**Comment by vipear** [comment]
What is your view on the number of envelope settings? There are currently 19 settings which were for experimentation. There might not be enough difference between settings to warrant so many settings. The differences get smaller as the numbers get larger. Maybe pick -8,-4,-2,-1,0... etc? That would reduce the settings to 9, and they could be mapped as -4,-3,-2,-1,0... Could save a little wear and tear on the encoder knob since the most likely settings to be used will be closer to 0.

**Comment by ElectroTechnique** [comment]
I'm testing at the moment. Yes, I agree with you. Just enough to have enough noticeable effect between them. I think having it as a global setting rather than patch level is fine too, personally I would just set it to my taste and leave it.  It sounds very good. Perhaps you should offer it on PJRC! There are two other recent threads on exp envelopes and neither quite cut it.

Can you provide me with picture of the envelope shapes altogether sometime, like you have on your repository somewhere please - for the update to the User Manual. 

Also I've pushed some new code on ExpEnv-Dev, can you use this for further changes please.

**Comment by vipear** [comment]
They are free to use it if they please. I have scope pictures on my Github wiki, are they sufficient? I have a mathematical plot of an envelope with overlapping attack curves as well on the wiki which is probably better suited for a manual. If the number are eventually reduced I can generate another one with the desired attack curves.

**Comment by vipear** [comment]
By the way, is the release drop off OK with the time settings? Initially I made the time constant the same as the display setting which meant in that time interval the output would drop to ~37% of initial value (-8.7 dB). Now I have it set to two time constants so it drops to 13.5% (-17.4dB). The bias I added makes it stop a little earlier by setting the target to a bit below zero. It is arbitrary and somewhat subjective.

**Comment by ElectroTechnique** [comment]
Ok, I've tested the shapes. Yes -8, -4, -2, -1, 0, 1, 2, 4, 8  plus Linear are fine.

**Comment by ElectroTechnique** [comment]
Just out of interest, is it a straight-forward task to modify the `AudioSynthWaveformDc` object for an optional exponential shape? TSynth uses this for glide. Glides are again, based on capacitor charge/discharge rather than a linear response.

**Comment by vipear** [comment]
I put a plot of an envelope with 9 attack curves corresponding to -8,-4,-2,-1,0,1,2,4,8 on my assets branch; pics/ExpEnvelope_9Attacks.png
The exponential glide looks feasible, I had to work out some issues with truncation errors on some trial filter code. The filter used in the envelope generator always settles in a negative direction and worked OK. The glide function settles both in the positive and negative direction and the truncation error introduced a bias in one direction resulting in the target being reached going down but ending up a little short going up. A change in the filter form appears to have fixed that. I'll try to get something out within a week if I have enough spare time. I'm not sure how well an exponential glide (like a charging capacitor) will sound if it is used for pitch. Normally on an analog synth the frequency is controlled as 1V/octave whereas I think the software oscillator frequency is linearly controlled. This will make the pitch change very quickly at the start but settle very slowly at the end.

**Comment by vipear** [comment]
I just push a build with hex file onto my exp-glide branch that implements an exponential glide. I have the constructor defaulted to exponential mode with no hooks to change it from settings. The mode can be set with setMode(). Currently any change to mode is set to pending until the glide has finished. I did this because I have not looked into how that would affect the linear mode going back from exp mode. It behaves like the linear glide which I think sounds strange.  When a different key is pressed before the last glide has finished it immediately starts at what the last key would have settled to in pitch and then glides to the current key pitch. That behavior appears to be implemented outside of the dc object.

**Comment by ElectroTechnique** [comment]
Sounds good, sounds quite long at the end. How is CPU performance?

**Comment by vipear** [comment]
The long settling was expected as the exponential is driving a linear pitch which is different than on an analog synth that has a 1V/octave pitch control. To cut it off a little early would require the driving target to be just beyond the actual target (like the attack on an envelope). Currently the full range of the integer math is being used as in the linear case. There is no room to go beyond that for a virtual target. I could look at re-scaling the math so it could work but it may require separating the variables for the linear and exponential cases. The CPU usage for patch #1 and glide active looks like it may go from 46 linear  to 47 exponential. I have pushed a build onto the branch that has the cpu monitor output enabled.

**Comment by ElectroTechnique** [comment]
Ok, this sounds good and I'd like to merge this with [https://github.com/ElectroTechnique/TSynth-Teensy4.1/tree/Master+MT](https://github.com/ElectroTechnique/TSynth-Teensy4.1/tree/Master+MT)

**Comment by ElectroTechnique** [comment]
Vince, the glide seems stuck in exponential mode, can you check this please:
` FLASHMEM void setMode(uint8_t mode)`
 ` {`
  `  // For now the mode should only change when the state is zero so set it to pending.`
`    // Changing mode from GLIDE_EXP to GLIDE_LIN may mess up the calculations.`
`    if(modePending!= GLIDE_EXP)` <--------------THIS PART
`      this->modePending=GLIDE_LIN; //default to linear for all other values.`
`    else this->modePending=GLIDE_EXP; // may have to wait until next state==0 for this to be set.`
`  }`
`  uint8_t getMode() { return mode;};`

Thanks.

**Comment by ElectroTechnique** [comment]
I think it's:
`if(mode!= GLIDE_EXP) `

**Comment by vipear** [comment]
Yes, I think you are right, that needs to be fixed. 
I haven't had much time to check the glide function fully but I think there maybe a problem if the glide parameter n is set subsequently to large differing values. For example, setting it to 1.0 and the to -1.0 after it settles may cause an overflow, at least in the exp section. A quick fix is to substitute the normal subtraction of magnitude and target with a saturating subtraction. The side effect of this is that for large differences between magnitude and target the transition may be slew rate limited initially. From what I have observed the target always to appear to be zero so the difference is never greater than 1.0 and may not be a problem. However, I want to make sure it works with the full range of magnitude to target values and try to avoid slew rate limiting.

**Comment by winder** [comment]
There is a parameter mixup in the settings

https://github.com/ElectroTechnique/TSynth-Teensy4.1/blob/b7540dea1368346669444ee8c901f3af88352207/TSynth/Settings.h#L127

**Comment by ElectroTechnique** [comment]
The branches are different, I'm now trying to merge two together manually, where there's been too many changes.

**Comment by winder** [comment]
If you put my changes in a separate branch I can merge exp env into it. Just tell me which branches to merge

**Comment by ElectroTechnique** [comment]
Ok, hang on, I'll be done within a few minutes. Yes, I do a new branch with exponential glide plus your current push/pull

[Master+MT](https://github.com/ElectroTechnique/TSynth-Teensy4.1/tree/Master+MT) should be be same as the branch you've just worked on [https://github.com/winder/TSynth-Teensy4.1/tree/will/dynamic-voice-num](https://github.com/winder/TSynth-Teensy4.1/tree/will/dynamic-voice-num)

**Comment by ElectroTechnique** [comment]
Ok can you use [https://github.com/ElectroTechnique/TSynth-Teensy4.1/tree/Master%2BMT%2BExpGlide](https://github.com/ElectroTechnique/TSynth-Teensy4.1/tree/Master%2BMT%2BExpGlide) to develop from please. This should have code from your last pull request and Vince's exp glide. The exp envelopes were already merged a while back.

**Comment by ElectroTechnique** [comment]
Github claimed it could merge the two branches without conflict, but it was over-writing changes whether merging from one to the other or vice-versa. Probably my fault...

**Comment by winder** [comment]
git can be fickle :laughing:

**Comment by vipear** [comment]
I just pushed to my exp-glide branch a new exp glide version and hex file. It should glide from -1.0 to 1.0 and back. It also includes a parameter EXP_TARGET_MARGIN that defines the amount over target overshoot so the settling tail isn't so long. I have it set to .01 (1% overshoot) and it is noticeable. It tried it with values up to 1.0 (100%) and it appeared to still work but I think that gliding from -1.0 to 1.0 at 100% overshoot may run out of integer range. Its probably not too useful at that value. I will pull the latest ExpGlide branch and work it in if that is still valid.

**Comment by ElectroTechnique** [comment]
Ok, by the way the latest Teensyduino 1.54 beta 9 works fine, but you need to delete data_bandlimit_step.c from the TSynth folder. I am moving to compiling with this.

**Pull request merged**
