### PR TITLE
Move monophonic priorities to a class.

### PR DESCRIPTION
**Pull request by winder**
This should fix some issues relating to monophonic mode.

I'm also starting to experiment with the platformio unit testing features. Hopefully this doesn't interfere with the Arduino IDE. The tests run with `platformio test -e native`:
```
$ platformio test -e native
Verbose mode can be enabled via `-v, --verbose` option
Collected 2 items

Processing test_desktop in native environment
--------------------------------------------------------------------------------------------------------------
Building...


Testing...
test/test_desktop/test_notestack.cpp:101:test_function_push	[PASSED]
test/test_desktop/test_notestack.cpp:102:test_function_erase_end	[PASSED]
test/test_desktop/test_notestack.cpp:103:test_function_erase_middle	[PASSED]
test/test_desktop/test_notestack.cpp:104:test_function_get_last	[PASSED]
test/test_desktop/test_notestack.cpp:105:test_function_get_first	[PASSED]
test/test_desktop/test_notestack.cpp:106:test_function_get_highest_1	[PASSED]
test/test_desktop/test_notestack.cpp:107:test_function_get_highest_2	[PASSED]
test/test_desktop/test_notestack.cpp:108:test_function_get_lowest_1	[PASSED]
test/test_desktop/test_notestack.cpp:109:test_function_get_lowest_2	[PASSED]

-----------------------
9 Tests 0 Failures 0 Ignored
OK
========================================= [PASSED] Took 0.57 seconds =========================================

Test          Environment    Status    Duration
------------  -------------  --------  ------------
test_desktop  native         PASSED    00:00:00.566
======================================== 1 succeeded in 00:00:00.566 ========================================
```

### CODE REVIEW

**Comment by ElectroTechnique** [comment]
Working fine in Arduino IDE. This has fixed the non-sounding monophonic patch problem.

**Comment by ElectroTechnique** [comment]
Ok, I spoke too soon. Playing a series of monophonic notes in quick succession locks everything up with noise - crash.

**Comment by winder** [comment]
> Ok, I spoke too soon. Playing a series of monophonic notes in quick succession locks everything up with noise - crash.

How quick? I mashed a bunch of notes and it was working fine, I'll have to do more testing.

**Comment by ElectroTechnique** [comment]
Just a few seconds of playing a load of notes. It is a crash, the sound plays continuously and the is no further response.

**Comment by winder** [comment]
@ElectroTechnique I'm still not able to reproduce this. Let's continue discussion here: https://github.com/ElectroTechnique/TSynth-Teensy4.1/discussions/97#discussioncomment-773996

**Pull request merged**
