### PR TITLE
Fix white noise.

### PR DESCRIPTION
**Pull request by winder**

### CODE REVIEW

**Comment by ElectroTechnique** [comment]
Some oddness with voices 10 and 11 not sounding,

**Comment by ElectroTechnique** [comment]
Voice 10 is intermittent, 11 never sounds.

**Comment by ElectroTechnique** [comment]
and sometimes it does...

**Comment by ElectroTechnique** [comment]
Patch 43 - 303 reliably doesn't sound voice 11

**Comment by winder** [comment]
I haven't seen this recently

**Comment by ElectroTechnique** [comment]
Set it to patch 2 and keep pressing a note until it cycles through all 12 a couple of times. Usually 10 or 11 or both will stop sounding.

**Pull request merged**
